# Generated by Django 2.1.7 on 2019-02-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_details',
            old_name='brach',
            new_name='branch',
        ),
    ]
